version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv export requirements-txt > requirements.txt
      - pip install -r requirements.txt

sphinx:
  configuration: docs/conf.py
