version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
      - pip install uv
      - uv export --format requirements-txt > requirements.txt
sphinx:
  configuration: docs/conf.py
