# Generated by Django 5.0.7 on 2024-07-17 17:31

import attachments.models.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=attachments.models.fields.BlobField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
            ),
        ),
    ]
